# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
pre_install do |installer|
    def installer.verify_no_static_framework_transitive_dependencies; end
    Pod::PodTarget.send(:define_method, :static_framework?) { return true }
end
inhibit_all_warnings!
#use_frameworks!
use_modular_headers!
workspace 'YHAsynDisplayKitDemo'



target 'YHAsynDisplayKitDemo' do
    project 'YHAsynDisplayKitDemo'
    pod 'YHAsynDisplayKit', :path => '../'
    pod 'SnapKit'
end

target 'YHAsynDisplayKit' do
    project '../YHAsynDisplayKit/YHAsynDisplayKit'
    pod 'SDWebImage', :modular_headers => true
    
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '5.0'
            config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
        target.build_settings(config.name)['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
            if config.name == 'Debug'
#              config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)', '-Onone']
#              config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule'
            end
        end
    end
end
